# Generated by Django 4.1.7 on 2023-02-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrv_value', models.IntegerField()),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('DR', 'Daily Record'), ('MR', 'Morning Record'), ('BT', 'Before Training'), ('AT', 'After Training'), ('AT5', '5 min After Training'), ('AT15', '15 min After Training'), ('AT30', '30 min After Training')], default='DR', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
